variable "region" { type = string; default = "ap-southeast-2" }
variable "cluster_name" { type = string; default = "task-manager-cluster" }
variable "environment" { type = string; default = "production" }
variable "vpc_cidr" { type = string; default = "10.0.0.0/16" }
variable "instance_type" { type = string; default = "t3.medium" }
variable "node_instance_type" { type = string; default = "t3.medium" }
variable "desired_nodes" { type = number; default = 2 }
variable "min_nodes" { type = number; default = 1 }
variable "max_nodes" { type = number; default = 3 }
variable "key_name" { type = string; default = "jenkins-key" }
