apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-alerts
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
    - name: backend.rules
      rules:

        - alert: HighErrorRate
          expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "High error rate on backend"
            description: "More than 10% of requests are returning 5xx errors"

        - alert: PodDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod is down"
            description: "A pod has been down for more than 1 minute"